{
 "title": "HotROD - Metrics and Logs Overview",
 "tags": [
  "Loki",
  "logging",
  "prometheus",
  "metrics",
  "jaeger",
  "hotrod"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "container_name",
    "label": "Service",
    "query": "label_values({container_name=~\".+\"}, container_name)"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)", "query": "error" }
  ]
 },
 "panels": [
  { "title": "Loki Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total  Count of logs",
   "type": "singlestat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=\"$container_name\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of pattern $searchable_pattern",
   "type": "singlestat",
   "description": "Total Count: of pattern: $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=\"$container_name\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{container_name=\"$container_name\"} |~ \"(?i)$searchable_pattern\" "
    }
   ]
  },
  {
   "title": "Percentage of \"$searchable_pattern\"  for specified time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=\"$container_name\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({container_name=\"$container_name\"})[$__interval]))",
     "legendFormat": "%"
    }
   ]
  },
  { "title": "Frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Frontend HTTP response codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hotrod_frontend_http_requests_total[5m])",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Frontend requests total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hotrod_frontend_requests_total[5m])",
     "legendFormat": "{{endpoint}} error: {{error}}"
    }
   ]
  },
  {
   "title": "Frontend request latency count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(hotrod_frontend_request_latency_count[5m])",
     "legendFormat": "{{endpoint}} - error: {{error}}"
    }
   ]
  },
  {
   "title": "Frontend latency percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(hotrod_frontend_request_latency_bucket[5m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(hotrod_frontend_request_latency_bucket[5m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(hotrod_frontend_request_latency_bucket[5m])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  { "title": "Route", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Route HTTP response codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hotrod_route_http_requests_total[5m])",
     "legendFormat": "{{status_code}} {{endpoint }} "
    }
   ]
  },
  {
   "title": "Route requests total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hotrod_route_requests_total[5m])",
     "legendFormat": "{{endpoint }} {{error}}"
    }
   ]
  },
  {
   "title": "Route request latency count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(hotrod_route_request_latency_count[5m])",
     "legendFormat": "{{endpoint}} - error: {{error}}"
    }
   ]
  },
  {
   "title": "Route latency percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(hotrod_route_request_latency_bucket[5m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(hotrod_route_request_latency_bucket[5m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(hotrod_route_request_latency_bucket[5m])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  { "title": "Customer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Customer HTTP response codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hotrod_customer_http_requests_total[5m])",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Customer requests total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hotrod_customer_requests_total[5m])",
     "legendFormat": "{{endpoint}} {{error}}"
    }
   ]
  },
  {
   "title": "Customer request latency count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(hotrod_customer_request_latency_count[5m])",
     "legendFormat": "{{endpoint}} - error: {{error}}"
    }
   ]
  },
  {
   "title": "Customer latency percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(hotrod_customer_request_latency_bucket[5m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(hotrod_customer_request_latency_bucket[5m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(hotrod_customer_request_latency_bucket[5m])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  { "title": "Driver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Driver HTTP response codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hotrod_driver_http_requests_total[5m])",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Driver HTTP response codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hotrod_driver_requests_total[5m])",
     "legendFormat": "{{endpoint}} error: {{error}}"
    }
   ]
  },
  {
   "title": "Driver request latency count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(hotrod_driver_request_latency_count[5m])",
     "legendFormat": "{{endpoint}} - error: {{error}}"
    }
   ]
  },
  {
   "title": "Driver latency percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(hotrod_driver_request_latency_bucket[5m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(hotrod_driver_request_latency_bucket[5m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(hotrod_driver_request_latency_bucket[5m])) by (le))",
     "legendFormat": "P50"
    }
   ]
  }
 ]
}