# Common docker compose for ok scoring kafka mq service

version: '3.1'

services:
  ok-scoring-zookeeper:
    container_name: ok-scoring-zookeeper
    image: bitnami/zookeeper:3
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  ok-scoring-kafka:
    container_name: ok-scoring-kafka
    image: bitnami/kafka:3
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=ok-scoring-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://ok-scoring-kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - ok-scoring-zookeeper
    ports:
      - '9093:9093'
    healthcheck:
      start_period: 30s
      test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "ok-scoring-kafka:9092"]
    volumes:
      - ok-scoring-kafka:/bitnami/kafka

volumes:
  ok-scoring-kafka:
